### PR TITLE
Force show/hide of summarySlide by using override flags

### PR DESCRIPTION
**Pull request by francisfueconcillo**
To hide summary slide, check "Enable override for "Show solution" and "Retry" settings." and uncheck Enable "Show solution" buttons.

### CODE REVIEW

**Comment by falcon-git** [comment]
Thanks for contributing. We would prefer a separate checkbox for controlling the summary slide.

The override button is intended to be used for toggling solutions as you go through the presentation on or off, but not to control the summary slide. I might be useful to have the summary slide there both when solutions are displayed as you go and when they are unavailable until you reach the summary slide. But it might also be useful to be able to disable the summary slide and/or disable the show solutions button on the summary slide.

**Comment by francisfueconcillo** [comment]
Ok. In that case, it might need a separate checkbox.

Can you point to me how to add a new checkbox? I tried adding in semantics.json (presentation) but I am not sure when those values are rendered.

Thanks.

**Comment by falcon-git** [comment]
Normally adding it to semantics.json would do the trick, but CP is a special case since it has its own editor widget (H5PEditor.CoursePresentation) for the presentation group (the first group in the semantics)

However I think this option belongs in the override group so I would do the following:
1. Change the label of the override group to "Behavior"
2. Change the label in the language files as well
3. Add the checkbox to the top of the "Behavior" group.
4. Add labels and other translatables to the translation files.

**Comment by francisfueconcillo** [comment]
Suggested changes done. 

News "Hide Summary Slide" in Behaviour (override) group added.

**Comment by thomasmars** [comment]
Hi francisfueconcillo!
I'm sure many users needs the functionality of disabling the summary slide :) I have merged your pull request in and it should be released shortly.
Thanks for your contribution, look forward to seeing more from you! :+1:

**Pull request merged**
