### PR TITLE
Fix F5 key triggered by presentation device laser pointer

### PR DESCRIPTION
**Pull request by otacke**

### CODE REVIEW

**Comment by fnoks** [comment]
Do I understand this one correct: When using a device, it triggers an F5, and the browser window is refreshed?

**Comment by otacke** [comment]
@fnoks You do.

**Comment by fnoks** [comment]
Then I think the problem is the pointer device, and it feels really strange adding code for this inside an H5P content type.

**Comment by otacke** [comment]
@fnoks It's a Kensington Wireless Presenter which I have seen quite often, and F5 is commonly used on some keys because it starts the presentation in PowerPoint. It's a bummer that hitting that key will reload the presentation in a browser IMHO.

**Comment by fnoks** [comment]
So, this is clearly a product not made for the web. We should not add code inside H5P content types to fix this. I would instead check if it was possible to configure the device to stop sending F5.

**Comment by otacke** [comment]
@fnoks Fine with me. But I know that people use H5P in non-web contexts, e.g. live presentations, and keys to start a PowerPoint presentation on presenter sticks may mess up the presenting person's performance.

**Pull request closed without merging**
